# Generated by Django 2.2.1 on 2020-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
